### PR TITLE
Proposal: Update issue templates

### PR DESCRIPTION
**Pull request by nqthqn**
This could come in handy for contributors and end users

### CODE REVIEW

**Comment by nqthqn** [comment]
Thoughts on adding a `.github` folder with this metadata? I figure you probably think it's a bit messy. But github respects it and it can help guide the project as people in the community create new issues.

**Comment by champagneabuelo** [comment]
Didn't know about this feature until Nathan brought it up, but I think it would be really useful for all future contributors! There's even a little tool that can auto-generate all the files for us: https://github.com/rhysd/dot-github

**Comment by daved** [comment]
I'm content with this so long as it's only text-based data and removed/updated if the repo hosting is ever changed.

**Comment by mckelveygreg** [comment]
@nqthqn Do you want to merge this or set this as a remote to the new reop?

**Pull request merged**
