### PR TITLE
Adding myself to the AUTHORS file

### PR DESCRIPTION
**Pull request by annag42**
Looks like this can probably be merged, and is signed. 
Please let me know if otherwise.

### CODE REVIEW

**Comment by annag42** [comment]
This addresses issue #158.

**Comment by codegold79** [comment]
It looks like GitHub Actions checks are failing. I'm guessing it is because our Actions are not set up to receive PRs from forks. We can ask @daved, but I think if you could create another PR but using a branch pushed up to OpenEugene/openboard, that would be easiest for our project. 

I'm afraid your signature couldn't be verified due to email mismatch. Are both your git global and non-global config emails set to the same one your GPG key was created with? 
Screenshot from 2021-07-29 18-22-54

**Comment by annag42** [comment]
Interesting, thanks for pointing that out. 
Right now, it looks like I'm in the main branch locally of my local (copy of the) repository, and "git config --list" shows the appropriate no-reply github-issued email address, while "git config --global --list" doesn't show any email address at all (which is how I'd prefer to keep it if possible).
I did just look, and it seems the box to keep my email address(es) private was un-checked, so i re-checked it. 
Maybe I should try re-committing? Or, rolling back and the re-doing the commit? 
Or maybe the push just needs to happen again?

**Comment by annag42** [comment]
Oh, maybe it's already verified, now that the checkbox is checked again.

**Comment by codegold79** [comment]
I can see you're verfied now, @annag42. 

Now, let's see about the next issue: "All checks have failed". I think I remember @daved saying forked branches will cause checks to fail. Would you be able to push the branch on your local machine to OpenEugene/openboard's repository? Then, open a new PR with that copy of the branch. Checks should pass at that point. If not, I guess we'll go from there.

**Comment by annag42** [comment]
Okay, I pushed directly here from my local machine. I now see it listed here as the one (current) commit, in the "Commits" tab. Is that what you meant? Did that cue the expected string of processes?

**Comment by annag42** [comment]
On second thought, maybe that's saying that there's just one commit in *this* pull request. So, there might still be additional required actions for me to complete (the propagation of) this signed commit, such as my somehow creating a pull request based on my push today from my local machine. Not sure how to do that. Though, maybe that's what's supposed to happen automagically?

**Comment by annag42** [comment]
Also, I wonder if it might be useful for me to try creating a new pull request from my fork, more recently than checking that checkbox, since some part of the process might only be cued by creating a pull request. Perhaps that would involve closing this one first, possibly by "Close with comment", then trying again from my fork.

**Comment by annag42** [comment]
Closing this pull request, so I can try again, likely twice:
first, from my own fork, now that my signature and email are aligned,
second, from my local machine to this upstream (shared) remote.

**Pull request closed without merging**
